spring.application.name=gymnex

# Configuração do Banco de Dados H2 (Em Memória)
spring.datasource.url=jdbc:h2:mem:gymnexdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Permite que o Spring crie e atualize as tabelas automaticamente
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

server.port=8081

# Aumentando os limites do servidor para processar strings Base64 sem barrar o payload
server.tomcat.max-http-form-post-size=20MB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB